### ISSUE TITLE
this.socket.destroy is not a function

### ISSUE THREAD

**Issue by gajus** [TooTallNate/node-https-proxy-agent#81]
After upgrading to v3, I started to get errors:

```
TypeError: this.socket.destroy is not a function
    at ClientRequest.abort (_http_client.js:328:17)
    at Immediate.timeoutHandler (/srv/node_modules/got/source/utils/timed-out.js:66:11)
    at processImmediate (internal/timers.js:441:21)
    at process.topLevelDomainCallback (domain.js:131:23)

```

So far I wasn't able to isolate what is causing them.

**Comment by lpinca** [comment]
I think it is caused by this https://github.com/TooTallNate/node-https-proxy-agent/blob/3.0.0/index.js#L171. To fix https://hackerone.com/reports/541502, a fake socket is now returned to the client if the proxy server does not respond with 200.

I wonder if using a `Duplex` instead of a plain `EventEmitter` fixes this issue. Can you try this patch?

```diff
diff --git a/index.js b/index.js
index aeb624d..0d7ca15 100644
--- a/index.js
+++ b/index.js
@@ -5,7 +5,7 @@
 var net = require('net');
 var tls = require('tls');
 var url = require('url');
-var events = require('events');
+var stream = require('stream');
 var Agent = require('agent-base');
 var inherits = require('util').inherits;
 var debug = require('debug')('https-proxy-agent');
@@ -168,7 +168,10 @@ HttpsProxyAgent.prototype.callback = function connect(req, opts, fn) {
                        //
                        // See: https://hackerone.com/reports/541502
                        socket.destroy();
-                       socket = new events.EventEmitter();
+                       socket = new stream.Duplex({
+        read() {},
+        write() {}
+      });
 
                        // save a reference to the concat'd Buffer for the `onsocket` callback
                        buffers = buffered;
```

**Comment by gajus** [comment]
I have not been able to replicate this issue in isolation. Cannot deploy a patch to production. I have added it to local development, but I have not really seen this happen locally.

**Comment by gajus** [comment]
Any plans on releasing this patch?
